version: "3.9"

services:

  enrichment-api:
    build: ./enrichment-api
    container_name: enrichment-api
    env_file:
      - enrichment-api.env
    ports:
      - "9999:9999"
    networks:
      - data-enrichment

  logstash:
    build: ./logstash
    container_name: logstash
    env_file:
      - logstash.env
    ports:
      - "9998:9998"
      - "9996:9996"
    volumes:
      - type: bind
        source: ./logstash/config
        target: /usr/share/logstash/config
        read_only: false
      - type: bind
        source: ./logstash/logs
        target: /usr/share/logstash/logs
        read_only: false
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: false
    networks:
      - data-enrichment

networks:
  data-enrichment:
    