apis:
  Abuse IP DB:
    endpoint: https://api.abuseipdb.com/api/v2/check
    field-mapping: {}
    headers:
      Accept: application/json
      Key: ${ABUSE_IP_DB_API_KEY}
    method: GET
    name: Abuse IP DB
    query-params:
      ${IP_ADDRESS_VARIABLE}: ipAddress
      maxAgeInDays: '90'
    use: true
  Fraud Sentinel:
    endpoint: https://api.fraudsentinel.com/api/sentinel.json
    field-mapping: {}
    method: GET
    name: Fraud Sentinel
    query-params:
      ${IP_ADDRESS_VARIABLE}: ip
      api_token: ${FRAUD_SENTINEL_API_KEY}
    use: true
  IP Quality Score:
    endpoint: https://ipqualityscore.com/api/json/ip
    field-mapping: {}
    method: GET
    name: IP Quality Score
    query-params:
      ${IP_ADDRESS_VARIABLE}: ip
      allow_public_access_points: true
      fast: false
      key: ${IP_QUALITY_SCORE_API_KEY}
      light_penalties: true
      mobile: false
      strictness: 0
    use: true
  IP Reputation:
    endpoint: https://ip-reputation-geoip-and-detect-vpn.p.rapidapi.com/
    field-mapping: {}
    headers:
      X-RapidAPI-Host: ip-reputation-geoip-and-detect-vpn.p.rapidapi.com
      X-RapidAPI-Key: ${IP_REPUTATION_API_KEY}
    method: GET
    name: IP Reputation
    query-params:
      ${IP_ADDRESS_VARIABLE}: ip
    use: true
  OTX Alien Vault:
    endpoint: https://otx.alienvault.com/api/v1/indicators/IPv4/${IP_ADDRESS_VARIABLE}/general
    field-mapping: {}
    headers:
      X-OTX-API-KEY: ${OTX_ALIEN_VAULT_API_KEY}
    method: GET
    name: OTX Alien Vault
    use: true
    vars:
      endpoints:
      - https://otx.alienvault.com/api/v1/indicators/IPv4/${IP_ADDRESS_VARIABLE}/general
      - https://otx.alienvault.com/api/v1/indicators/IPv4/${IP_ADDRESS_VARIABLE}/reputation
      - https://otx.alienvault.com/api/v1/indicators/IPv4/${IP_ADDRESS_VARIABLE}/geo
      - https://otx.alienvault.com/api/v1/indicators/IPv4/${IP_ADDRESS_VARIABLE}/malware
      - https://otx.alienvault.com/api/v1/indicators/IPv4/${IP_ADDRESS_VARIABLE}/url_list
      - https://otx.alienvault.com/api/v1/indicators/IPv4/${IP_ADDRESS_VARIABLE}/passive_dns
  Proxy Check:
    endpoint: http://proxycheck.io/v2/${IP_ADDRESS_VARIABLE}
    field-mapping: {}
    method: GET
    name: Proxy Check
    query-params:
      asn: 1
      days: 7
      key: ${PROXY_CHECK_API_KEY}
      node: 1
      port: 1
      risk: 1
      seen: 1
      short: 0
      time: 1
      vpn: 1
    use: true
  VPN API:
    endpoint: https://vpnapi.io/api/${IP_ADDRESS_VARIABLE}
    field-mapping: {}
    headers: {}
    method: GET
    name: VPN API
    query-params:
      key: ${VPN_API_KEY}
    use: true
