version: 1
disable_existing_loggers: False
incremental: False
formatters:
  simple:
    '()': 'colorlog.ColoredFormatter'
    format: '%(asctime)s %(log_color)s%(bold)s%(levelname)-7s%(reset)s [%(purple)s%(process)d%(reset)s] %(cyan)s%(name)-25s%(reset)s %(message)s'
    datefmt: "%d-%b-%Y@%H:%M%z"
  verbose:
    format: "[%(asctime)s] <%(levelno)2d>%(levelname)-7s %(name)-10s [%(process)d] %(processName)-20s %(message)s"
    datefmt: "%d-%b-%YT%T%z"
  syslog-format:
    format: "%(name)-10s %(module)-16s [%(process)d] %(processName)-20s %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  file_hd:
    class: logging.handlers.RotatingFileHandler
    filename: ${LOG_FILE_PATH:/var/log/data-enrichment.log}
    formatter: verbose
    level: DEBUG
    mode: a
    maxBytes: 50000000
    backupCount: 4
  syslog:
    class: logging.handlers.SysLogHandler
    level: DEBUG
    address: [ "127.0.0.1", 514 ]
    socktype: ext://socket.SOCK_DGRAM
    facility: "user"
    formatter: syslog-format
loggers:
  enrichment-api:
    level: DEBUG
    handlers: [console, file_hd, syslog]
    propagate: no
    name: data-enrichment
root:
  level: DEBUG
  handlers: [console, file_hd, syslog]