access_log: true
additional_settings:
  READ ME: Move settings you want to configure to the root of this file
  app_dir: None
  env_file: None
  fd: None
  forwarded_allow_ips: None
  h11_max_incomplete_event_size: DEFAULT_MAX_INCOMPLETE_EVENT_SIZE
  headers: None
  limit_concurency: None
  limit_max_requests: None
  log_config: None
  log_level: None
  reload_dirs:
  - None
  reload_excludes:
  - None
  reload_includes:
  - None
  ssl_ca_certs: None
  ssl_cert_reqs: int(ssl.CERT_NONE)
  ssl_certfile: None
  ssl_keyfile: None
  ssl_keyfile_password: None
  ssl_version: int(SSL_PROTOCOL_VERSION)
  uds: None
  workers: None
backlog: 2048
date_header: true
debug: false
factory: false
host: ${UVICORN_HOST}
http: auto
interface: auto
lifespan: auto
loop: auto
port: ${UVICORN_PORT}
proxy_headers: true
reload: true
reload_delay: 0.25
root_path: ''
server_header: true
ssl_ciphers: TLSv1
timeout_keep_alive: 5
use_colors: true
ws: auto
ws_max_size: 16777216
ws_per_message_deflate: true
ws_ping_interval: 20
ws_ping_timeout: 20
