version: 1
disable_existing_loggers: False
incremental: False
formatters:
  simple:
    '()': 'colorlog.ColoredFormatter'
    format: '%(asctime)s %(log_color)s%(bold)s%(levelname)-7s%(reset)s [%(purple)s%(process)d%(reset)s] %(cyan)s%(name)-25s%(reset)s %(message)s'
    datefmt: "%d-%b-%Y@%H:%M%z"
handlers:
  default:
    formatter: simple
    class: logging.StreamHandler
    stream: ext://sys.stderr 
  access:
    formatter: simple
    class: logging.StreamHandler
    stream: ext://sys.stdout
loggers:
  uvicorn.error:
    level: DEBUG
    handlers:
      - default
    propagate: no 
  uvicorn.access:
    level: DEBUG
    handlers:
      - access
    propagate: no
root:
  level: DEBUG
  handlers:
    - access