node.name: docker_logstash_1
xpack.monitoring.enabled: true
xpack.management.elasticsearch.cloud_id: ${ELASTIC_CLOUD_ID}
xpack.management.elasticsearch.username: ${ELASTIC_USERNAME}
xpack.management.elasticsearch.password: ${ELASTIC_PASSWORD}